### ISSUE TITLE
Change Name

### ISSUE THREAD

**Issue by AstroWLAN** [giovannidispoto/Santorini#9]
@giovannidispoto can you change the name of the repo to Santorini?
Plis. 
![Sad-Hamster-thumbnail-url-8gmiw7](https://github.com/user-attachments/assets/7ed1b2a1-14c7-4a40-b888-2a2f89f89bfc)

**Comment by giovannidispoto** [comment]
Done

**Comment by AstroWLAN** [comment]
Thanks for your hard work. 
Keep it up truly inspiring!
